import NavBar from "../../components/nav/navbar"
import Head from "next/head"
import SectionCards from "../../components/card/section-cards"
import styles from '../../styles/MyList.module.css'
import RedirectUser from "../../utils/redirectUser"
import { getMyListVideos } from "../../lib/videos"

export async function getServerSideProps(context) {
  const { userId, token } = await RedirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }
  
  const myListVideos = await getMyListVideos(userId, token);
 
  return {
    props: {
      myListVideos
    }
  }
}

const MyList = (props) => {
  const { myListVideos } = props;
  return (
    <div>
      <Head>
        <title>My List</title>
        <meta name="Netflix clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
          <div className={styles.sectionWrapper}>
            <SectionCards shouldWrap title='My List' videos={myListVideos} size='small'/>
          </div>
      </main>
      
    </div>
  )
}

export default MyList