import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner/banner'
import NavBar from '../components/nav/navbar'
import SectionCards from '../components/card/section-cards'
import { getDisneyVideos, getTravelVideos, getProductivityVideos, getPopularVideos
} from '../lib/videos'

export async function getServerSideProps() {
  const disneyVideos = getDisneyVideos();
  const productivityVideos = getProductivityVideos();
  const travelVideos = getTravelVideos();
  const popularVideos = getPopularVideos();

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos
    }
  }
}

export default function Home(props) {
  const { disneyVideos, productivityVideos, travelVideos, popularVideos } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Notflix</title>
        <meta name="Netflix clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username='user@gmail.com'/>
      <Banner 
        title='Haunting of Ed'
        subTitle="Don't turn back"
        imgUrl='/static/ed.jpg' 
        videoId = 'sVZUr5XmAec'
       />
      <div className={styles.sectionWrapper}>
        <SectionCards title='Disney' videos={disneyVideos} size='large'/>
        <SectionCards title='Productivity' videos={productivityVideos} size='medium'/>
        <SectionCards title='Travel' videos={travelVideos} size='medium'/>
        <SectionCards title='Popular' videos={popularVideos} size='small'/>
      </div>

    </div>
  )
}
