import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner/banner'
import NavBar from '../components/nav/navbar'
import SectionCards from '../components/card/section-cards'
import { getDisneyVideos, getTravelVideos, getProductivityVideos,
   getPopularVideos
} from '../lib/videos'
import { getWatchItAgainVideos } from '../lib/videos'

export async function getServerSideProps(context) {
  const userId = 'did:ethr:0x67dd71A73682F0023caEc8A99A2c57Ec00Aa63e4';
  const token = context.req ? context.req?.cookies.token : null;

  const disneyVideos = getDisneyVideos();
  const productivityVideos = getProductivityVideos();
  const travelVideos = getTravelVideos();
  const popularVideos = getPopularVideos();

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
      watchItAgainVideos
    }
  }
}

export default function Home(props) {
  const { disneyVideos, productivityVideos, travelVideos, popularVideos, watchItAgainVideos } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Notflix</title>
        <meta name="Netflix clone" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar username='user@gmail.com'/>
      <Banner 
        title="Can't even play minecraft in Ohio"
        subTitle="I wish I kid"
        imgUrl='/static/background.png' 
        videoId = 'FtZAS9gtqcs'
       />
      <div className={styles.sectionWrapper}>
        { 
          watchItAgainVideos.length > 0 && 
          <SectionCards title='Watch It Again' videos={watchItAgainVideos} size='small'/> 
        }
        <SectionCards title='Disney' videos={disneyVideos} size='small'/>
        <SectionCards title='Productivity' videos={productivityVideos} size='small'/>
        <SectionCards title='Travel' videos={travelVideos} size='small'/>
        <SectionCards title='Popular' videos={popularVideos} size='small'/>
      </div>

    </div>
  )
}
